In [1]:
import json
import numpy as np
import cv2

jsonTrainFile = "Data/ship/transforms_train.json"

with open(jsonTrainFile, "r") as fp:
    jsonTrainData = json.load(fp)

print(f"Field of view in X direction - train: {jsonTrainData['camera_angle_x']}")
print(f"Number of frames - train: {len(jsonTrainData['frames'])}")

Field of view in X direction - train: 0.6911112070083618
Number of frames - train: 100


In [2]:
first_frame = jsonTrainData["frames"][0]

# transformation matrix and related image
transform_matix = np.array(first_frame["transform_matrix"])
file_name = first_frame["file_path"]

print(transform_matix)  # This the Camera-World transform matrix for the respective image.
print(file_name)  # Respective image file path
print(f"Rotation {first_frame['rotation']}")

[[-4.65905853e-02  1.75296515e-01 -9.83412623e-01 -3.96426296e+00]
 [-9.98914063e-01 -8.17604642e-03  4.58675772e-02  1.84898108e-01]
 [-9.31322575e-10  9.84481692e-01  1.75487086e-01  7.07411051e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
./train/r_0
Rotation 0.012566370614359171


In [3]:
img = cv2.imread('Data/ship/train/r_0.png')
cv2.imshow('image', img)
cv2.waitKey(0)

-1